### PR TITLE
Transfer {dynamic_repo_module, dynamic_repo} across processes

### PR DESCRIPTION
**Pull request by spacebat**
This allows for the info used in Ecto.Repo.put_dynamic_repo\1 to carry over to the process actually performing the query.

# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
This should be doable with a custom tracer as discussed here: https://elixirforum.com/t/using-an-ash-resource-with-a-dynamic-repository/61138/4?u=zachdaniel

**Comment by zachdaniel** [comment]
Ah, I see the issue is that you don't have the query. Perhaps we can expand the tracer api to get the subject being used to start a new process.

**Comment by zachdaniel** [comment]
Actually your preparation to set the process context and a custom tracer together should do what you want.

**Comment by spacebat** [comment]
Zach was right, the tracer approach worked

**Pull request closed without merging**
